import cv2

SOURCE_FOLDER = "img"

WIDTH_SIZE = 28
HEIGTH_SIZE = 28

INTERPOLATION_MODE = cv2.INTER_AREA

RESULT_LIST = list()

CSV_RESULT_FILE_NAME = "output.csv"

CSV_END_POINT = "{}".format(CSV_RESULT_FILE_NAME)